title: Database of Greek and Latin Conjectural Emendations Attested in MSS
description: A hard look at the soft practice of textual criticism
logo: /assets/android-chrome-192x192.PNG
locale: en_GB
url: "https://t18d.github.io/attested-conjectures"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
