name: Open Source by Tonkünstler-on-the-Bund
title: null
description: A hard look at the soft practice of textual criticism
locale: en_GB
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
    values:
      seo:
        type: WebPage
