title: Open Source by Tonkünstler-on-the-Bund
author:
  type: Organization
  name: TKB
  url: https://www.tonkunstler-on-the-bund.com
locale: en_GB
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
incremental: true
exclude: [greek.csv, latin.csv, biblical.csv, csv-to-md.py, csv_tools.py, txt-to-csv.py, xml-to-md.py, LICENSE]
