title: Database of Greek and Latin Conjectural Emendations Attested in MSS
description: A hard look at the soft practice of textual criticism
logo: /assets/favicon.ico
locale: en_GB
plugins:
  - jekyll-seo-tag
