name: Run csv-to-md.py
run-name: csv-to-md
on: 
  push:
    paths:
      - "*.csv"
      - csv-to-md.py
jobs:
  Run-CSV-To-MD_PY:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - run: python csv-to-md.py
      - uses: stefanzweifel/git-auto-commit-action@v4
