name: Run csv-to-md.py
run-name: csv-to-md
on: 
  push:
    paths:
      - "*.csv"
jobs:
  Run-CSV-To-MD_PY:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
      - run: python csv-to-md.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
    # Optional. Commit message for the created commit.
    # Defaults to "Apply automatic changes"
          commit_user_name: git-auto-commit-action
