name: Run csv-to-md.py
run-name: csv-to-md
on: 
  push:
    branches: ['main']
    paths:
      - "*.csv"
jobs:
  Run-CSV-To-MD_PY:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          # Partially clone against a given filter. Overrides sparse-checkout if set.
          # Default: null
          sparse-checkout: |
            scripts/
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.x'
      - run: |
          python scripts/csv-to-md.py
          sed -i "0,/last_modified_at.*/s//last_modified_at: $(date -Iseconds)/" README.md
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
    # Optional. Commit message for the created commit.
    # Defaults to "Apply automatic changes"
          commit_user_name: git-auto-commit-action
