name: Run csv-to-md.py
run-name: csv-to-md
on: 
  push:
    paths:
      - attested-conjectures.csv
jobs:
  Run-CSV-To-MD_PY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - uses: stefanzweifel/git-auto-commit-action@v4
      - run: python csv-to-md.py
